#+TITLE: Java/Heroku
#+STYLE: <link rel="stylesheet" type="text/css" href="http://nick.gs/orgstyle.css">
#+OPTIONS: toc:nil

* Java/Heroku

This project is a testbed to explore writing Java Webapps and hosting them on Heroku.

[[http://aqueous-refuge-9456.herokuapp.com/][It is currently hosted on Heroku]], but it's on the free plan. That means the first request might take a while
as they will put my app to sleep if it gets no traffic for a while.

* Endpoints
- /letters
- /letters?letters=word
  Spells out a word, putting a : in front of every character. Used for forum emoticons
- /test
- /test?name=xxx&age=xxx
  dumps a json object, with correct headers!
- /name
- /name?name=xxx
  print a greeting. Very "Hello World".
- * wildcard
  another "hello world" endpoint
* Tech

I started by following the Heroku Java quickstart guide. That explains how to write a simple Java
application that uses Jetty to handle http traffic. I then wrote a few servlets to experiment with.
The whole thing is built and managed by Maven. It's been great so far!

* Problems

I am running into a lot of problems with `foreman`. It is not stopping the server correctly.
Java still runs in the background and stays attached to the port. I always have to kill
the process or be lazy and assign a new port then go back and kill a bunch of Java processes
later.

A workaround is to use `honcho` and that seems to take care of things.
